In [2]:
import cv2   # opencv is a library used for computer vision

In [3]:
import numpy as np

In [4]:
img= cv2.imread("C:\\Users\\Brij\\Desktop\\govind madhav keshari.jpg",1)  # 1 for colored. 0 for grey scale image

In [5]:
# colored img is 3D and greyScale(black & white) img is 2D array

In [6]:
print(img)

[[[ 47  38  28]
  [ 87  78  65]
  [ 84  70  52]
  ...
  [ 81  69  51]
  [ 94  81  67]
  [ 52  41  27]]

 [[ 42  33  20]
  [251 240 226]
  [208 193 174]
  ...
  [221 207 189]
  [255 243 227]
  [ 37  26  12]]

 [[ 40  27  11]
  [228 214 196]
  [198 180 157]
  ...
  [188 173 154]
  [231 218 202]
  [ 40  27  11]]

 ...

 [[ 28  21  24]
  [199 194 196]
  [236 234 240]
  ...
  [178 161 165]
  [254 238 245]
  [ 37  23  29]]

 [[ 34  32  32]
  [183 182 184]
  [239 243 248]
  ...
  [172 158 162]
  [234 222 228]
  [ 37  25  31]]

 [[ 33  33  33]
  [ 56  58  59]
  [ 59  66  69]
  ...
  [ 67  56  59]
  [ 66  54  60]
  [ 51  41  47]]]


In [7]:
print(type(img))

<class 'numpy.ndarray'>


In [8]:
print(img.shape)  # for colored img there is 3 channels RGB

(350, 350, 3)


In [9]:
print(img.size)

367500


In [10]:
# showing the image

In [11]:
cv2.imshow('Keshari',img)

cv2.waitKey(0)  # 0 meanes user has to press any key to close the window

#cv2.waitKey(2000)  # it means window will wait for 2000 mili sec and then close

cv2.destroyAllWindows()

In [12]:
# resizing

In [13]:
resized_img= cv2.resize(img, (600,600))

cv2.imshow('Madhav',resized_img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [14]:
print(resized_img.shape)

(600, 600, 3)


In [15]:
# we can half or double or give any size to original image according to our convinence.

In [16]:
resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))    # i can also multiply bt it 2

cv2.imshow('Govind',resized_img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [17]:
print(resized.shape)

(175, 175, 3)


# Face Detection

In [18]:
# image --> create a cascade classifier, it will contain features of the face(it will determine where is the face)
# --> opencv --> numpy array(search for row n column values of the face (face rectangle coordinates))
# --> display the image with rectangular face box

In [1]:
import cv2

#cv2.CascadeClassifier.load("haarcascade_frontalface_default.xml")

# create a CascadeClassifier object
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")

face_cascade.load("haarcascade_frontalface_default.xml")


True

In [2]:
# Reading the image as it is
image = cv2.imread("C:\\Users\\Brij\\Desktop\\govind madhav keshari.jpg",1)

#Reading the image as gray scale image 
gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Search for the face rectangle coordinates of the image
faces = face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)

print(type(faces))
print(faces)  # coordinates of the face


# same thing to detect eyes
eyes = eye_cascade.detectMultiScale(gray_img)

for ex,ey,ew,eh in eyes:
    cv2.rectangle(image, (ex,ey), (ex+ew,ey+eh), (255,0,0), 2)
    
    

# for adding rectangle to face we r using for loop
for (x,y,w,h) in faces:
    image = cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,0), 3)
    
cv2.imshow('Gray', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
[[102  59 138 138]]


In [21]:
# Capture video using openCV

In [22]:
import cv2,time

video = cv2.VideoCapture(0)

# we need to create a frame object , which will read the images of the VideoCapture object
# we will recessively show each frame of the video being captured

check,frame= video.read()
print(check)
print(frame)

time.sleep(3)

cv2.imshow('captured',frame)
cv2.waitKey(0)

video.release()

cv2.destroyAllWindows()

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [23]:
# lets add a window that shows the video   (for above cell)

# check : is a bool data type, returns true if Python is able to read the VideoCapture object

# frame : is a Numpy array, it represents the first image that video captures

In [24]:
# till now we just captured the first frame 
# how to capture the video, instead of First image/Frame of the video??
# for that we r going to use a loop

# in order to capture the video, we will be using the 'while' loop. While condition will be such that,
# ultil unless 'check' is True, Python will display the frames.

In [25]:
import cv2,time

video= cv2.VideoCapture(0)
a=1

while True:
    a=a+1
    check,frame=video.read()
    print(frame)
    gray= cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # convert the frame into a gray scale image
    cv2.imshow('capturing',gray)
    key=cv2.waitKey(1)  # this will generate a new frame after every 1 milisec.
    if key==ord('q'):   # once we enter q the window will be destroyed
        break
        
print(a)  # this will print the no. of frames
video.release()
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


In [26]:
# Use case : Motion Detector

In [27]:
# problem statement : u hav been approached a company that is studying human behaviour. ur task is to give them a webcam
#  that can detect the motion or any movement in front of it. This should return a graph, this graph should contain for 
# how long the human/object was in front of the camera.

In [28]:
# flow diagram of use case:
# start--->save the initial image in a frame--->convert this image to a gaussian blur image--->
# take the frames with the object & convert it into gaussian blur image--->cal. the diffc--->
# define the threshold to remove the shadows & other noises--->define the borders of the object--->
# add the rectangular box around the object--->cal. the time, when object appears and exits the frame 

In [1]:
import cv2,time,pandas

first_frame = None
video = cv2.VideoCapture(0)
while True:
    check,frame = video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray=cv2.GaussianBlur(gray,(21,21),0)
    
    if first_frame is None:
        first_frame=gray
        continue

    delta_frame = cv2.absdiff(first_frame,gray)
    # cal. the diffrnc between first frame and other frames 


    thresh_delta = cv2.threshold(delta_frame, 30, 255, cv2.THRESH_BINARY)[1]
    thresh_delta = cv2.dilate(thresh_delta,None,iterations=0)
    # provides a threshold value, such that it will convert the diffrence value less than 30 to black. 
    # if the diffrnce is greater than 30 it will convert those pixels to white



    cnts,_ = cv2.findContours(thresh_delta.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    # define the contour area basically, add the borders



    for contour in cnts:
        if cv2.contourArea(contour)<1000:
            continue
        x,y,w,h=cv2.boundingRect(contour)
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0),3)
    

    
    cv2.imshow('Frame',frame)
    cv2.imshow('Capturing',gray)
    cv2.imshow('delta',delta_frame)
    cv2.imshow('thresh',thresh_delta)

    key = cv2.waitKey(1)
    if key==ord('q'):
        break
video.release()
cv2.destroyAllWindows()


        

In [30]:
# cal. the time for which the object was in front of the camera

In [31]:
from motion_detector import df  # import it fromm the motion_detector module that u created

ModuleNotFoundError: No module named 'motion_detector'

In [ ]:
# bokeh is a library used to visualize the data on the browser

In [33]:
from bokeh.plotting import figure,show,output_file

In [34]:
from bokeh.models import HoverTool, ColumnDataSource